name: Report a new commit
on:
  push:
    branches:
      - master

jobs:
  report:
    if: "contains(github.event.head_commit.message, 'KEEP-')"
    runs-on: ubuntu-latest
    steps:
      - name: Get list of issues
        run: >-
          echo ::set-output name=LIST::$(
          echo "$COMMIT_MESSAGE"
          | grep -oE "^KEEP\-[0-9]+"
          | jq -Rsc '{issues:[split("\n")|unique|.[]|select(length > 0)]}' )
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        id: issues

      - name: Report a new commit
        run: |
          curl -X POST -H 'Content-type: application/json' --data "$ISSUES_LIST" "$HOOKS_URL/$HOOK_MERGE"
        env:
          ISSUES_LIST: ${{ steps.issues.outputs.LIST }}
          HOOKS_URL: ${{ secrets.HOOKS_URL }}
          HOOK_MERGE: ${{ secrets.HOOK_MERGE }}
